name          'shoekstra-apticron'
version       '0.1.0'
source        'https://github.com/shoekstra/puppet-apticron'
author        'shoekstra'
license       'Apache License, Version 2.0'
summary       'apticron puppet module'
description   'Puppet module to install and configure Apticron, a simple script which sends daily emails about pending package updates on Debian based systems.'
project_page  'https://github.com/shoekstra/puppet-apticron'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
